export const dashboardCopy = {
  common: {
    requestFailed: 'Request failed. Please try again.',
    saveChanges: 'Save changes',
    cancel: 'Cancel',
    confirmAction: 'Confirm',
  },
  header: {
    title: 'Task Dashboard',
    signedInAs: 'Signed in as',
    signOut: 'Sign out',
  },
  tasks: {
    sectionTitle: 'Tasks',
    listView: 'List',
    kanbanView: 'Kanban',
    timelineView: 'Timeline',
    newTask: 'New task',
    refreshing: 'Refreshing...',
    noEmployees: 'No employees available. Please create an employee first.',
    create: 'Create task',
    edit: 'Edit',
    delete: 'Delete',
    overdue: 'Overdue',
    duePrefix: 'Due:',
    subtasksPrefix: 'Subtasks:',
    donePrefix: 'Done:',
    createdToastTitle: 'Task created',
    updatedToastTitle: 'Task updated',
    updatedToastDescription: 'Your changes have been saved.',
    deletedToastTitle: 'Task deleted',
    createdToastDescription: (title: string): string => `"${title}" has been created.`,
    deletedToastDescription: (title: string): string => `"${title}" has been deleted.`,
    confirmDeleteTitle: 'Delete task',
    confirmDelete: (title: string): string => `Delete task "${title}"?`,
    editHeading: (taskId: number | string): string => `Edit task #${taskId}`,
    missingContext: 'Task context is missing.',
    validations: {
      titleRequired: 'Title is required.',
      startDateRequired: 'Start date is required.',
      assigneeRequired: 'Assignee is required.',
      subtaskInvalid: 'Each subtask requires a title and start date.',
    },
  },
  subtasks: {
    title: 'Subtasks',
    noSubtasks: 'No subtasks yet.',
    addPlaceholder: 'Add subtask...',
    add: 'Add',
    addSubtask: 'Add subtask',
    noSubtasksAdded: 'No subtasks added.',
    titlePlaceholder: 'Subtask title',
    remove: 'Remove',
    start: 'Subtask start',
    end: 'Subtask end',
    assignedTo: 'Assigned to',
    unassigned: 'Unassigned',
    completed: 'Completed',
    removeAria: (title: string): string => `Remove subtask ${title}`,
  },
  employees: {
    workspaceControls: 'Workspace Controls',
    filterDescription: 'Filter the board by assigned employee.',
    noEmployees: 'No employees available yet. Please create one first.',
    refreshData: 'Refresh data',
    managementTitle: 'Employee management',
    addEmployee: 'Add employee',
    createEmployee: 'Create employee',
    editEmployee: 'Edit employee',
    edit: 'Edit',
    removeEmployee: 'Remove',
    employeeFilter: 'Employee filter',
    allEmployees: 'All employees',
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email',
    role: 'Role',
    department: 'Department',
    noEmployeesYet: 'No employees yet.',
    createdToastTitle: 'Employee created',
    updatedToastTitle: 'Employee updated',
    deletedToastTitle: 'Employee deleted',
    createdToastDescription: (employeeName: string): string => `${employeeName} has been created.`,
    updatedToastDescription: (employeeName: string): string => `${employeeName} has been saved.`,
    deletedToastDescription: (employeeName: string): string => `${employeeName} has been deleted.`,
    confirmDeleteTitle: 'Delete employee',
    confirmDelete: (employeeName: string): string => `Delete employee "${employeeName}"?`,
    editAria: (employeeName: string): string => `Edit employee ${employeeName}`,
    removeAria: (employeeName: string): string => `Remove employee ${employeeName}`,
    validations: {
      firstNameRequired: 'First name is required.',
      lastNameRequired: 'Last name is required.',
      emailRequired: 'Email is required.',
    },
  },
} as const;
